const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const link=p=>`<a href="#app/inventory/${p.id}">${esc(p.name)}</a>`;
export function simpleInsights(state,list,{money,icon}){
  const days=list[0]?.days||Math.min(28,Math.max(1,Math.floor((Date.now()-Date.parse(state.observationStart))/86400000)));
  const sold=list.reduce((n,i)=>n+i.sold,0);
  const low=list.filter(i=>i.available<=i.product.reorderPoint).sort((a,b)=>a.available-b.available);
  const restock=list.filter(i=>i.recommendation>0||i.available<=i.product.reorderPoint).sort((a,b)=>a.available-b.available);
  const best=list.filter(i=>i.sold>0).slice(0,4),max=Math.max(1,...best.map(i=>i.sold));
  const slow=list.filter(i=>i.sold===0&&i.onHand>0).sort((a,b)=>b.onHand-a.onHand);
  const sales=state.orders.filter(o=>o.status==='Fulfilled'&&Date.parse(o.fulfilledAt)>Date.now()-28*86400000&&Date.parse(o.fulfilledAt)<=Date.now());
  const revenue=sales.reduce((n,o)=>n+o.lines.reduce((v,l)=>v+l.quantity*l.priceCents,0),0);
  const movements=state.movements.filter(m=>m.delta!==0&&m.reason!=='Opening stock').slice(-5).reverse();
  const blank=(copy)=>`<p class="insight-empty">${copy}</p>`;
  const restockRow=i=>`<li><div>${link(i.product)}<small>${i.available} ready to sell${i.incoming?` &middot; ${i.incoming} arriving`:''}</small></div><span class="insight-order ${i.recommendation?'':'on-way'}">${i.recommendation?`Order ${i.recommendation}`:'On the way'}</span></li>`;
  const slowRow=i=>`<li><div>${link(i.product)}<small>No recorded sales in ${days} days</small></div><span class="insight-quantity">${i.onHand}<small>in stock</small></span></li>`;
  const categories=new Map();for(const i of list)categories.set(i.product.category,(categories.get(i.product.category)||0)+i.sold);
  const categoryRows=[...categories].filter(([,n])=>n>0).sort((a,b)=>b[1]-a[1]);
  const colors=['#2878ef','#129a88','#80b7fb','#83cdbf','#a9b6c7'];let position=0;
  const slices=categoryRows.map(([,n],index)=>{const start=position;position+=sold?n/sold*100:0;return `${colors[index%colors.length]} ${start}% ${position}%`;});
  const buckets=Array.from({length:7},(_,index)=>{const d=new Date();d.setDate(d.getDate()-6+index);return {key:d.toISOString().slice(0,10),label:d.toLocaleDateString('en-US',{weekday:'short'}),count:0};});
  for(const o of sales){const bucket=buckets.find(b=>b.key===o.fulfilledAt.slice(0,10));if(bucket)bucket.count+=o.lines.reduce((n,l)=>n+l.quantity,0);}
  const high=Math.max(1,...buckets.map(b=>b.count)),week=buckets.reduce((n,b)=>n+b.count,0);
  const points=buckets.map((b,index)=>`${25+index*48},${100-b.count/high*65}`).join(' ');
  return `<header class="page-heading"><div><div class="eyebrow">BARGETOWN AT A GLANCE</div><h1>What needs your attention?</h1><p>See what is selling and what to stock next.</p></div><span class="insight-period">Last ${days} days &middot; recorded sales</span></header>
  <div class="simple-insights">
    <section class="card store-insight"><div class="store-insight-cover"><span>YOUR STORE SNAPSHOT</span>${icon('inventory')}</div><div class="store-insight-body"><div class="store-insight-mark">${esc(state.settings.name.split(' ').slice(0,2).map(w=>w[0]).join(''))}</div><h2>${esc(state.settings.name)}</h2><p>Your shelves, in a few numbers.</p><div class="store-insight-numbers"><div><strong>${state.products.length}</strong><span>products</span></div><div><strong class="${low.length?'attention-number':''}">${low.length}</strong><span>running low</span></div></div><a href="#app/inventory" class="button secondary">Check inventory</a></div></section>
    <section class="card insight-bestsellers"><div class="card-heading"><div><h2>Customers are buying</h2><p>Most units sold in ${days} days</p></div>${icon('insights')}</div><div class="insight-bars">${best.map((i,index)=>`<div><div class="insight-bar-label">${link(i.product)}<b>${i.sold}<small> sold</small></b></div><div class="insight-bar-track"><span style="width:${i.sold/max*100}%;background:${colors[index%colors.length]}"></span></div></div>`).join('')||blank('No completed sales yet. Fulfill a sales order to see your best sellers.')}</div></section>
    <section class="card insight-timeline"><div class="card-heading"><div><h2>Recently in your store</h2><p>Latest sales and stock changes</p></div></div><ol>${movements.map(m=>{const p=state.products.find(p=>p.id===m.productId);return `<li><span class="timeline-marker ${m.delta>0?'received':''}">${m.delta>0?'+':'−'}</span><div><b>${Math.abs(m.delta)} ${m.delta>0?'added':m.reason==='Order fulfilled'?'sold':'removed'}</b><p>${p?link(p):'Product unavailable'}</p><small>${esc(m.reason)}${m.related?` &middot; ${esc(m.related)}`:''}</small><time>${new Date(m.at).toLocaleString('en-US',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})}</time></div></li>`;}).join('')||blank('No stock changes yet. Sales and deliveries will appear here.')}</ol></section>
    <section class="card insight-restock"><div class="card-heading"><div><h2>Restock next</h2><p>A short list for your next delivery</p></div><span class="insight-count">${restock.length}</span></div><ul class="insight-product-list">${restock.slice(0,4).map(restockRow).join('')||blank('Stock looks ready. No additional units are suggested right now.')}</ul>${restock.length>4?`<details class="insight-more"><summary>See ${restock.length-4} more items</summary><ul class="insight-product-list">${restock.slice(4).map(restockRow).join('')}</ul></details>`:''}<div class="insight-card-foot"><p>Incoming deliveries are already included in these suggestions.</p><a class="text-link" href="#app/purchasing">Plan a delivery</a></div></section>
    <section class="card insight-week"><div class="card-heading"><div><h2>This week's sales</h2><p>Units sold each day &middot; last 7 days</p></div></div><div class="insight-big-number">${week}<span>items sold</span></div><svg viewBox="0 0 340 145" role="img" aria-label="Units sold over the last seven days; daily values are listed below"><path d="M25 100H313" stroke="#e8eef3"/><polyline points="${points}" fill="none" stroke="#2878ef" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/>${buckets.map((b,index)=>`<circle cx="${25+index*48}" cy="${100-b.count/high*65}" r="3" fill="#2878ef"/><text x="${25+index*48}" y="126" text-anchor="middle">${b.label}</text>`).join('')}</svg><div class="insight-daily-values">${buckets.map(b=>`<span><small>${b.label}</small><b>${b.count}</b></span>`).join('')}</div></section>
    <section class="card insight-slow"><div class="card-heading"><div><h2>Not selling yet</h2><p>Stock with no recorded sales in ${days} days</p></div></div><ul class="insight-product-list">${slow.slice(0,3).map(slowRow).join('')||blank('Every stocked product has a recorded sale in this period.')}</ul>${slow.length>3?`<details class="insight-more"><summary>See ${slow.length-3} more products</summary><ul class="insight-product-list">${slow.slice(3).map(slowRow).join('')}</ul></details>`:''}<p class="insight-card-note">Check shelf space before buying more. For fresh food, check freshness and prep needs.</p></section>
    <section class="card insight-sales-total"><div class="card-heading"><div><h2>Recorded sales</h2><p>Completed sales over the last ${days} days</p></div></div><div class="insight-big-number">${money(revenue)}<span>${sold} items sold &middot; before tax</span></div><p class="insight-card-note">Only fulfilled orders count. This is a demo record, not a connected checkout total.</p></section>
    <section class="card insight-categories"><div class="card-heading"><div><h2>What shoppers choose</h2><p>Share of units sold &middot; ${days} days</p></div></div>${sold?`<div class="insight-category-body"><div class="insight-donut" style="background:conic-gradient(${slices.join(',')})" aria-hidden="true"><span><b>${sold}</b><small>sold</small></span></div><ul>${categoryRows.map(([name,n],index)=>`<li><i style="background:${colors[index%colors.length]}"></i><span>${esc(name)}</span><b>${Math.round(n/sold*100)}%</b></li>`).join('')}</ul></div>`:blank('Record a sale to see which categories shoppers choose.')}</section>
  </div><details class="insight-method"><summary>How do we decide what to restock?</summary><p>We suggest enough to reach your minimum stock level. When there are at least 14 days of history and sales on 3 different days, we also allow for 7 days of recent sales. Stock already reserved or arriving is included.</p><p>Ready to sell means physical stock minus units reserved for pickups. Estimates combine all locations. Missing sales or empty shelves can make demand look lower than it is.</p><div class="table-scroll"><table><thead><tr><th>Product</th><th>Estimated stock remaining</th></tr></thead><tbody>${list.map(i=>`<tr><td>${link(i.product)}</td><td>${i.daysLeft===null?'Not enough data':`${i.daysLeft.toFixed(1)} days at the recent sales pace`}</td></tr>`).join('')}</tbody></table></div><p>Days remaining = units ready to sell divided by the average units sold per day over ${days} observed days. These are simple sales-based estimates.</p></details>`;
}
