import assert from 'node:assert/strict';
import {completeSale,salesInsights,readStore,inventoryKey} from '../sales-data.mjs';
const now=Date.parse('2026-10-06T18:00:00Z');
const store={items:[{sku:'a',name:'Bread',quantity:20,unit:'loaves',reorderPoint:5}],sales:[],isSample:false};
assert.throws(()=>completeSale(store,{id:'1',status:'pending',lines:[{sku:'a',quantity:2}]}),/paid/);
assert.throws(()=>completeSale(store,{id:'1',status:'paid',lines:[{sku:'a',quantity:21}]}),/Not enough/);
assert.throws(()=>completeSale(store,{id:'1',status:'paid',lines:[{sku:'missing',quantity:1}]}),/Unknown/);
assert.throws(()=>completeSale(store,{id:'1',status:'paid',lines:[{sku:'a',quantity:0}]}),/positive/);
const next=completeSale(store,{id:'1',status:'paid',at:new Date(now).toISOString(),lines:[{sku:'a',quantity:2},{sku:'a',quantity:3}]});
assert.equal(next.items[0].quantity,15);assert.equal(store.items[0].quantity,20);
assert.equal(next.sales[0].lines[0].before,20);assert.equal(next.sales[0].lines[0].after,15);
assert.equal(completeSale(next,{id:'1',status:'paid',lines:[{sku:'a',quantity:5}]}),next);
assert.equal(salesInsights(next,now)[0].current,5);
assert.equal(salesInsights(next,now)[0].enoughHistory,false);
const history={...next,items:[{...next.items[0],quantity:0}],sales:[{id:'old',at:new Date(now-15*86400000).toISOString(),lines:[{sku:'a',quantity:1}]},{id:'previous',at:new Date(now-8*86400000).toISOString(),lines:[{sku:'a',quantity:2}]},next.sales[0]]};
const insight=salesInsights(history,now)[0];
assert.equal(insight.trend,'Selling faster');assert.equal(insight.enoughHistory,true);assert.equal(insight.suggested,5);
const saved=JSON.stringify(next);assert.equal(readStore({getItem:key=>key===inventoryKey?saved:null}).sales.length,1);
console.log('Passed: paid-only deduction, stock validation, atomic calculation, duplicate event prevention, movement history, and trend suggestions.');
